hide_window_decorations yes
# hide_window_decorations titlebar-only
font_size 12
# background_opacity 0.85
# background_blur 1
touch_scroll_multiplier 5.0

enabled_layouts Grid, *

# BEGIN_KITTY_FONTS
font_family      family="JetBrains Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# BEGIN_KITTY_THEME
# Catppuccin-Macchiato
include theme.conf
# END_KITTY_THEME

# Shell setup
shell zsh
